### ISSUE TITLE
ReadModelService: Input string was not in a correct format

### ISSUE THREAD

**Issue by trymh** [ProCoSys/Bifrost#68]
Missing validation?

GET     /Bifrost/ReadModel/InstanceMatching?_rm=Read.Completion.Tag.Tag

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt64(String value, NumberStyles options, NumberFormatInfo numfmt)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at Bifrost.Web.Read.ReadModelService.GetPropertyEqualsExpression(Type type, String propertyName, Object value) in C:\T\f0471d076df39445\Source\Bifrost.Web\Read\ReadModelService.cs:line 138
   at Bifrost.Web.Read.ReadModelService.InstanceMatching(ReadModelQueryDescriptor descriptor) in C:\T\f0471d076df39445\Source\Bifrost.Web\Read\ReadModelService.cs:line 85
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Bifrost.Web.Services.RestServiceMethodInvoker.Invoke(String baseUrl, Object instance, Uri uri, IDictionary`2 inputParameters) in C:\T\f0471d076df39445\Source\Bifrost.Web\Services\RestServiceMethodInvoker.cs:line 55
   at Bifrost.Web.Services.RestServiceRouteHttpHandler.ProcessRequest(HttpContext context) in C:\T\f0471d076df39445\Source\Bifrost.Web\Services\RestServiceRouteHttpHandler.cs:line 73

**Comment by bnordli** [comment]
Fixed by #69
